### ISSUE TITLE
可以分享一下cmeee V1版本的数据集吗

### ISSUE THREAD

**Issue by songxian1129** [YBRua/CMeEE#1]

**Comment by YBRua** [comment]
Hi，很抱歉，这只是一个课程期末作业的代码仓库，我并没有保留当时的 CMeEE 数据集。

我在 CBLUE 的官方数据集发布网站（[link](https://tianchi.aliyun.com/dataset/95414)）上看到 CMeEE-V2 相较于 CMeEE-V1 只是修正了一些标注错误，以及标注区间“从左闭右闭更新为左闭右开”，因此在数据集上应该没有特别大的差异？

如果你确实需要 CMeEE-V1 的数据集的话，可能你需要去别的地方找一下。或者我看到官方网站上仍然保留了旧版本的数据集（[CBLUE 2.0](https://tianchi.aliyun.com/dataset/145741?spm=a2c22.12282016.0.0.7a5d21955ObVHS)），这里面好像有 CMeEE-v1 数据集，也许你可以尝试申请使用这个？

**Comment by songxian1129** [comment]
好的 谢谢你
